### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by pkfranz** [CSIS-iLab/amti_2016#17]
Search should bring you to a clearer form for searching content vs. an anchor link to footer.

**Comment by jnschrag** [comment]
@pkfranz, One option for the search in the header menu is to have an expanding search bar like [this one](http://callmenick.com/_development/expanding-search-bar/#).

**Comment by pkfranz** [comment]
I like it.  Just keep in mind that the search currently is the right-most option on the page.  Can we easily flip the animation so the bar pulls toward the left?

**Comment by jnschrag** [comment]
Of course.
