### ISSUE TITLE
Refinements

### ISSUE THREAD

**Issue by pkfranz** [CSIS-iLab/amti_2016#29]
- [x] **Assign Grace to migrate user meta from live site to WPEngine staging;**
- User data didn't carry over with XML export, if there's a better way to export user meta, let's do that, but don't spend a lot of time on it if it's complicated. Headshots could use a second look anyway, with proper alt titles and better compression.

- [x] **Manual user profile pics**
- Did this with a plugin before, but we need to override the Gravatar default. (Open to more efficient suggestions.)
- https://wordpress.org/plugins/metronet-profile-picture/

- [x] **Use `nickname` on main posts index**

- [x] **Use manual excerpts for the posts index instead of the auto `the_excerpt`**.  This is probably another Grace/Willa task.  I want to avoid awkward char limits and ellipsis.

- [x] Remove the `Posted By` on the posts index byline and replace with just `By`, and no colon -- e.g. `By Paul Franz |`. The Center chafes at any hint of this being a "blog" (even though that's what it is...)

- [x] **Remove author bio box on `features` pages**

- [x] **Share buttons** - as discussed, let's just use a plugin for it. Under ideal conditions, we would do this ourselves, but let's just go with what works: https://wordpress.org/plugins/simple-share-buttons-adder/
1. Also add to feature posts

- [x] **Pagination for archive pages with more than the set post limit.**

- [x] **2FA implementation.**  We currently use Rublon, but I've had a better experience with Google Authenticator for WordPress.  What do you think? 

- [x] **Search results page looks awesome! Adjust the search bar so it pulls out under menu items.**

- [x] **Let's pull `category_description` to the category page under the `h1.page-title`**

- [x] **Pull in the static page content, e.g.** 
1. https://amti.csis.org/maps/
2. https://amti.csis.org/island-tracker/
3. https://amti.csis.org/about/

Open to any and all suggestions you may have on how to make these better.  Let's ignore the Features content until we have a better conversation with Greg on what he actually wants to keep.

- [x] **Test Jetpack/gallery output**
Pull down images from https://www.flickr.com/photos/139462176@N08/albums/72157671407461032 and see how well it works on one of these Island Tracker pages.  (Photos are open to download as a .zip)

- [x] **Mobile optimization**
Make minor adjustments to how pages scale on smaller viewports. I think we could stand to improve the current mobile experience we have on the site.  The NYT mobile app (e.g. https://www.luxurydaily.com/wp-content/uploads/2012/09/Ferragamo-NYT-app-ad.jpg) _feels_ right to me, but I'd like your opinion on this, too.

- [x] **add proper favicon**

- [x] **Move home page slider to header**
Only show it on static page as index

- [x] **Add link to edit home page slider in admin menu**

**Comment by jnschrag** [comment]
@pkfranz All the thoughts incoming...

*User Meta Data*
Let's do a custom export of the existing data and upload it to staging directly via phpmyadmin, overwriting the existing data in the users and usersmeta tables. We can have Grace go through and check the headshots and other information afterwards.

*Manual User Profile Pics*
I think using the plugin is fine.

*Use `nickname` on posts*
Do you mean "FirstName LastName"?

*Excerpts*
I can ask Grace to manually update the excerpts. What is a good guideline for her to follow for this? First paragraph of the post?

*Share Buttons*
I've tried the Simple Share Buttons that is currently being used by AMTI and Feather Share, neither of which showed share buttons on the featured pages despite advertising that they can show up on custom post types. Can you take a look at this one? I removed my code for it.

*2FA*
I'm fine with either. I've never used 2FA for WordPress prior to coming to CSIS, so I don't have any basis to compare different plugins.

*Pull in Static Content*
I can get Grace to help out with this. 

*Mobile Optimization*
I've been trying to test as I go along, but I can spend some time checking all the views to see what they look like.

**Comment by pkfranz** [comment]
1. On nickname: Yep!  Just something that's not the user slug.  I think `nicename` does exist as an option that is essentially just First, Last.  

2. First para, with maybe a max of two complete sentences so we're not defaulting to ellipsis or read more links.  Harder to judge this since sometimes the lede gets buried in these analytic posts.

3. Social share - no problem, I'll take a look!

4. Let's roll with Google Authenticator then.  Rublon is annoying and proprietary and has been causing more problems than it's worth.

5. Static content -- I'll see if I can get a meeting with Greg and Will to make some hard decisions on what to keep out of this.  In the meantime, let's research a good way to get from pages->custom post types.

6. Mobile optimization -- Let's make this a last priority while we fix all the interim bugs.

**Comment by pkfranz** [comment]
Social sharing now fixed

**Comment by jnschrag** [comment]
Installed Google Authenticator, so these should all be taken care of now.
