### ISSUE TITLE
Test Staff Editor access

### ISSUE THREAD

**Issue by pkfranz** [CSIS-iLab/amti_2016#35]
Walk through the admin panel with Ella to see permissions for Staff Editor.  Adjust as necessary.

**Comment by jnschrag** [comment]
- [ ] Cannot edit Analysis posts
- [ ] Cannot edit Featured posts
- [ ] Cannot edit Island Tracker posts
- [ ] Check redirects for submitting a feature and island tracker (currently redirecting to analysis listing)
- [ ] Cannot edit pages created by other users, can edit pages created by them

**Comment by pkfranz** [comment]
resolved -- removed all page access ... test during launch phase
