### ISSUE TITLE
Reorganize SASS files

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/amti_2016#5]
Proposed structure based on underscores default:

base/
	_typhography.scss (copy, headings, links)
	_variables.scss (colors, structure, typography)
	_normalize.scss
	_bootstrap.scss
	_base.scss

components/
	_forms.scss (buttons, fields)
	_tables.scss
	_media.scss (captions, galleries)
        _lists.scss
	_components.scss

layout/
	_header.scss
	_footer.scss
	_posts-and-pages.scss
	_comments.scss
	_widgets.scss
        _layout.scss

pages/
	*create .scss files for each custom page we have if they differ from the _posts-and-pages.scss*
_pages.scss

utils/
	_mixins.scss
	_accessibility.scss
	_alignments.scss
	_clearings.scss
	_infinite-scroll.scss
_utils.scss

style.scss

**Comment by jnschrag** [comment]
- [ ] Pull in Bootstrap

**Comment by jnschrag** [comment]
@pkfranz Do you want to keep the "Menu Icons" plugin? As far as I can tell, it is only used to get the search and twitter icons on the main menu, which should be possible with CSS.

**Comment by pkfranz** [comment]
@jnschrag Let's go ahead and use the font-awesome library.  That plugin is definitely deprecated.
