### ISSUE TITLE
Full page-width style for Features

### ISSUE THREAD

**Issue by pkfranz** [CSIS-iLab/amti_2016#58]
Create a method for content managers to embed/create elements that are full-page width vs. container width. 

1. Do we want to make it so that there is an automatic default for editors?
2. Is post-type a viable approach? (e.g. Container width post type, full-width post type with option to use container-width divs)

**Comment by jnschrag** [comment]
Another idea would be to create a short code that breaks the content within that shortcode out of the content container.
