### ISSUE TITLE
Image galleries in AMTI features are not being displaying correctly

### ISSUE THREAD

**Issue by jdromero88** [CSIS-iLab/amti_2016#91]
This [feature](https://amti.csis.org/vietnams-major-spratly-expansion/) from last year, here’s what the gallery looks like now vs. how it appeared originally
Now:
![image](https://github.com/CSIS-iLab/amti_2016/assets/51330062/cc59e3c8-05ee-4c63-a02e-b0eff58b1833)
Original:
![image](https://github.com/CSIS-iLab/amti_2016/assets/51330062/00ac9f36-7eae-4468-9536-d18675ff5598)

another [example](https://amti.csis.org/a-new-chinese-runway-in-the-paracels-probably-not/) where is not working. This may be related to the “mosaic” gallery option

**Comment by urchykli** [comment]
Fixed this while updating the PHP version.
